# Generated by Django 4.1.5 on 2023-01-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_degree_remove_customer_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='degree',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.tech', 'M.Tech')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='program',
            field=models.CharField(choices=[('ICT', 'ICT'), ('MnC', 'MnC'), ('DS', 'DS')], max_length=200, null=True),
        ),
    ]
