# Generated by Django 4.1.5 on 2023-01-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
