# Generated by Django 4.1.5 on 2023-01-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('company', models.CharField(max_length=200)),
                ('type_offer', models.CharField(max_length=200)),
                ('job_profile', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
    ]
