# Generated by Django 4.1.5 on 2023-01-27 17:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_experiences', '0002_experience_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
