# Generated by Django 4.1.5 on 2023-01-30 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview_experiences', '0004_experience_title_alter_experience_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='bookmark',
            field=models.ManyToManyField(default=None, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
